INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('ndt-inspection-track', 'Inspection & Non-Destructive Testing (NDT)', 'ndt-inspection', 'Master visual inspection, magnetic particle testing, and ultrasonic testing for professional certification.', 1, 'advanced', 40, 1766834874);
INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('diver-medic-track', 'Diver Medic Technician (DMT)', 'diver-medic', 'Emergency medical response, ABCDE assessment, and diving injury treatment certification.', 1, 'expert', 60, 1766834874);
INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('commercial-supervisor-track', 'Commercial Dive Supervisor', 'commercial-supervisor', 'Dive operations management, safety protocols, and emergency response leadership.', 1, 'expert', 50, 1766834874);
INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('saturation-diving-track', 'Saturation Diving Systems', 'saturation-diving', 'Saturation diving operations, life support systems, and decompression management.', 1, 'expert', 80, 1766834874);
INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('underwater-welding-track', 'Advanced Underwater Welding', 'underwater-welding', 'Professional underwater welding techniques, electrode selection, and quality control.', 1, 'advanced', 60, 1766834874);
INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('hyperbaric-operations-track', 'Hyperbaric Chamber Operations', 'hyperbaric-operations', 'Hyperbaric treatment protocols, emergency procedures, and patient monitoring.', 1, 'intermediate', 30, 1766834874);
INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('alst-track', 'Assistant Life Support Technician (ALST)', 'alst', 'Advanced life support operations, emergency decompression protocols, and saturation diving medical procedures.', 1, 'expert', 70, 1766834874);
INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('lst-track', 'Life Support Technician (LST)', 'lst', 'Life support system operations, gas management, and emergency response procedures.', 1, 'advanced', 50, 1766834874);
INSERT OR REPLACE INTO tracks (id, title, slug, summary, is_published, difficulty, estimated_hours, created_at) VALUES ('air-diver-track', 'Air Diver Certification', 'air-diver-certification', 'Essential air diving skills including diving physics review, gas management concepts, ascent best practices, problem-solving drills, tool handling safety, and basic communications.', 1, 'intermediate', 40, 1766834874);
