/**
 * Comprehensive list of timezones with major cities worldwide
 * Organized by timezone offset and region
 */

export interface TimezoneOption {
  value: string;
  label: string;
  city?: string;
  region?: string;
}

export const timezones: TimezoneOption[] = [
  // UTC
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)', city: 'London (GMT)', region: 'UTC' },
  
  // North America - Eastern
  { value: 'America/New_York', label: 'New York, USA', city: 'New York', region: 'Eastern Time' },
  { value: 'America/Toronto', label: 'Toronto, Canada', city: 'Toronto', region: 'Eastern Time' },
  { value: 'America/Montreal', label: 'Montreal, Canada', city: 'Montreal', region: 'Eastern Time' },
  { value: 'America/Detroit', label: 'Detroit, USA', city: 'Detroit', region: 'Eastern Time' },
  { value: 'America/Miami', label: 'Miami, USA', city: 'Miami', region: 'Eastern Time' },
  { value: 'America/Indianapolis', label: 'Indianapolis, USA', city: 'Indianapolis', region: 'Eastern Time' },
  { value: 'America/Boston', label: 'Boston, USA', city: 'Boston', region: 'Eastern Time' },
  { value: 'America/Philadelphia', label: 'Philadelphia, USA', city: 'Philadelphia', region: 'Eastern Time' },
  { value: 'America/Washington', label: 'Washington DC, USA', city: 'Washington', region: 'Eastern Time' },
  { value: 'America/Atlanta', label: 'Atlanta, USA', city: 'Atlanta', region: 'Eastern Time' },
  { value: 'America/Cancun', label: 'Cancún, Mexico', city: 'Cancún', region: 'Eastern Time' },
  { value: 'America/Havana', label: 'Havana, Cuba', city: 'Havana', region: 'Eastern Time' },
  { value: 'America/Nassau', label: 'Nassau, Bahamas', city: 'Nassau', region: 'Eastern Time' },
  { value: 'America/Port-au-Prince', label: 'Port-au-Prince, Haiti', city: 'Port-au-Prince', region: 'Eastern Time' },
  { value: 'America/Santo_Domingo', label: 'Santo Domingo, Dominican Republic', city: 'Santo Domingo', region: 'Eastern Time' },
  { value: 'America/Panama', label: 'Panama City, Panama', city: 'Panama City', region: 'Eastern Time' },
  { value: 'America/Bogota', label: 'Bogotá, Colombia', city: 'Bogotá', region: 'Eastern Time' },
  { value: 'America/Lima', label: 'Lima, Peru', city: 'Lima', region: 'Eastern Time' },
  { value: 'America/Guayaquil', label: 'Guayaquil, Ecuador', city: 'Guayaquil', region: 'Eastern Time' },
  { value: 'America/Caracas', label: 'Caracas, Venezuela', city: 'Caracas', region: 'Eastern Time' },
  { value: 'America/La_Paz', label: 'La Paz, Bolivia', city: 'La Paz', region: 'Eastern Time' },
  { value: 'America/Santiago', label: 'Santiago, Chile', city: 'Santiago', region: 'Eastern Time' },
  { value: 'America/Asuncion', label: 'Asunción, Paraguay', city: 'Asunción', region: 'Eastern Time' },
  
  // North America - Central
  { value: 'America/Chicago', label: 'Chicago, USA', city: 'Chicago', region: 'Central Time' },
  { value: 'America/Mexico_City', label: 'Mexico City, Mexico', city: 'Mexico City', region: 'Central Time' },
  { value: 'America/Winnipeg', label: 'Winnipeg, Canada', city: 'Winnipeg', region: 'Central Time' },
  { value: 'America/Dallas', label: 'Dallas, USA', city: 'Dallas', region: 'Central Time' },
  { value: 'America/Houston', label: 'Houston, USA', city: 'Houston', region: 'Central Time' },
  { value: 'America/New_Orleans', label: 'New Orleans, USA', city: 'New Orleans', region: 'Central Time' },
  { value: 'America/Minneapolis', label: 'Minneapolis, USA', city: 'Minneapolis', region: 'Central Time' },
  { value: 'America/Guatemala', label: 'Guatemala City, Guatemala', city: 'Guatemala City', region: 'Central Time' },
  { value: 'America/Managua', label: 'Managua, Nicaragua', city: 'Managua', region: 'Central Time' },
  { value: 'America/Costa_Rica', label: 'San José, Costa Rica', city: 'San José', region: 'Central Time' },
  { value: 'America/Tegucigalpa', label: 'Tegucigalpa, Honduras', city: 'Tegucigalpa', region: 'Central Time' },
  { value: 'America/El_Salvador', label: 'San Salvador, El Salvador', city: 'San Salvador', region: 'Central Time' },
  { value: 'America/Belize', label: 'Belize City, Belize', city: 'Belize City', region: 'Central Time' },
  
  // North America - Mountain
  { value: 'America/Denver', label: 'Denver, USA', city: 'Denver', region: 'Mountain Time' },
  { value: 'America/Phoenix', label: 'Phoenix, USA', city: 'Phoenix', region: 'Mountain Time' },
  { value: 'America/Edmonton', label: 'Edmonton, Canada', city: 'Edmonton', region: 'Mountain Time' },
  { value: 'America/Calgary', label: 'Calgary, Canada', city: 'Calgary', region: 'Mountain Time' },
  { value: 'America/Salt_Lake_City', label: 'Salt Lake City, USA', city: 'Salt Lake City', region: 'Mountain Time' },
  { value: 'America/Albuquerque', label: 'Albuquerque, USA', city: 'Albuquerque', region: 'Mountain Time' },
  
  // North America - Pacific
  { value: 'America/Los_Angeles', label: 'Los Angeles, USA', city: 'Los Angeles', region: 'Pacific Time' },
  { value: 'America/Vancouver', label: 'Vancouver, Canada', city: 'Vancouver', region: 'Pacific Time' },
  { value: 'America/San_Francisco', label: 'San Francisco, USA', city: 'San Francisco', region: 'Pacific Time' },
  { value: 'America/Seattle', label: 'Seattle, USA', city: 'Seattle', region: 'Pacific Time' },
  { value: 'America/Portland', label: 'Portland, USA', city: 'Portland', region: 'Pacific Time' },
  { value: 'America/Tijuana', label: 'Tijuana, Mexico', city: 'Tijuana', region: 'Pacific Time' },
  { value: 'America/Hermosillo', label: 'Hermosillo, Mexico', city: 'Hermosillo', region: 'Pacific Time' },
  
  // North America - Alaska & Hawaii
  { value: 'America/Anchorage', label: 'Anchorage, USA', city: 'Anchorage', region: 'Alaska Time' },
  { value: 'America/Juneau', label: 'Juneau, USA', city: 'Juneau', region: 'Alaska Time' },
  { value: 'Pacific/Honolulu', label: 'Honolulu, USA', city: 'Honolulu', region: 'Hawaii Time' },
  
  // South America
  { value: 'America/Sao_Paulo', label: 'São Paulo, Brazil', city: 'São Paulo', region: 'Brazil Time' },
  { value: 'America/Rio_de_Janeiro', label: 'Rio de Janeiro, Brazil', city: 'Rio de Janeiro', region: 'Brazil Time' },
  { value: 'America/Buenos_Aires', label: 'Buenos Aires, Argentina', city: 'Buenos Aires', region: 'Argentina Time' },
  { value: 'America/Montevideo', label: 'Montevideo, Uruguay', city: 'Montevideo', region: 'Uruguay Time' },
  { value: 'America/Cayenne', label: 'Cayenne, French Guiana', city: 'Cayenne', region: 'French Guiana Time' },
  { value: 'America/Fortaleza', label: 'Fortaleza, Brazil', city: 'Fortaleza', region: 'Brazil Time' },
  { value: 'America/Recife', label: 'Recife, Brazil', city: 'Recife', region: 'Brazil Time' },
  { value: 'America/Manaus', label: 'Manaus, Brazil', city: 'Manaus', region: 'Brazil Time' },
  
  // Europe - Western
  { value: 'Europe/London', label: 'London, UK', city: 'London', region: 'GMT/BST' },
  { value: 'Europe/Dublin', label: 'Dublin, Ireland', city: 'Dublin', region: 'GMT/BST' },
  { value: 'Europe/Lisbon', label: 'Lisbon, Portugal', city: 'Lisbon', region: 'GMT/BST' },
  { value: 'Europe/Madrid', label: 'Madrid, Spain', city: 'Madrid', region: 'CET/CEST' },
  { value: 'Europe/Paris', label: 'Paris, France', city: 'Paris', region: 'CET/CEST' },
  { value: 'Europe/Rome', label: 'Rome, Italy', city: 'Rome', region: 'CET/CEST' },
  { value: 'Europe/Berlin', label: 'Berlin, Germany', city: 'Berlin', region: 'CET/CEST' },
  { value: 'Europe/Amsterdam', label: 'Amsterdam, Netherlands', city: 'Amsterdam', region: 'CET/CEST' },
  { value: 'Europe/Brussels', label: 'Brussels, Belgium', city: 'Brussels', region: 'CET/CEST' },
  { value: 'Europe/Vienna', label: 'Vienna, Austria', city: 'Vienna', region: 'CET/CEST' },
  { value: 'Europe/Zurich', label: 'Zurich, Switzerland', city: 'Zurich', region: 'CET/CEST' },
  { value: 'Europe/Stockholm', label: 'Stockholm, Sweden', city: 'Stockholm', region: 'CET/CEST' },
  { value: 'Europe/Copenhagen', label: 'Copenhagen, Denmark', city: 'Copenhagen', region: 'CET/CEST' },
  { value: 'Europe/Oslo', label: 'Oslo, Norway', city: 'Oslo', region: 'CET/CEST' },
  { value: 'Europe/Helsinki', label: 'Helsinki, Finland', city: 'Helsinki', region: 'EET/EEST' },
  { value: 'Europe/Warsaw', label: 'Warsaw, Poland', city: 'Warsaw', region: 'CET/CEST' },
  { value: 'Europe/Prague', label: 'Prague, Czech Republic', city: 'Prague', region: 'CET/CEST' },
  { value: 'Europe/Budapest', label: 'Budapest, Hungary', city: 'Budapest', region: 'CET/CEST' },
  { value: 'Europe/Athens', label: 'Athens, Greece', city: 'Athens', region: 'EET/EEST' },
  { value: 'Europe/Bucharest', label: 'Bucharest, Romania', city: 'Bucharest', region: 'EET/EEST' },
  { value: 'Europe/Sofia', label: 'Sofia, Bulgaria', city: 'Sofia', region: 'EET/EEST' },
  { value: 'Europe/Moscow', label: 'Moscow, Russia', city: 'Moscow', region: 'MSK' },
  { value: 'Europe/Kiev', label: 'Kyiv, Ukraine', city: 'Kyiv', region: 'EET/EEST' },
  { value: 'Europe/Istanbul', label: 'Istanbul, Turkey', city: 'Istanbul', region: 'TRT' },
  
  // Middle East
  { value: 'Asia/Dubai', label: 'Dubai, UAE', city: 'Dubai', region: 'GST' },
  { value: 'Asia/Abu_Dhabi', label: 'Abu Dhabi, UAE', city: 'Abu Dhabi', region: 'GST' },
  { value: 'Asia/Riyadh', label: 'Riyadh, Saudi Arabia', city: 'Riyadh', region: 'AST' },
  { value: 'Asia/Jeddah', label: 'Jeddah, Saudi Arabia', city: 'Jeddah', region: 'AST' },
  { value: 'Asia/Kuwait', label: 'Kuwait City, Kuwait', city: 'Kuwait City', region: 'AST' },
  { value: 'Asia/Bahrain', label: 'Manama, Bahrain', city: 'Manama', region: 'AST' },
  { value: 'Asia/Qatar', label: 'Doha, Qatar', city: 'Doha', region: 'AST' },
  { value: 'Asia/Muscat', label: 'Muscat, Oman', city: 'Muscat', region: 'GST' },
  { value: 'Asia/Tehran', label: 'Tehran, Iran', city: 'Tehran', region: 'IRST' },
  { value: 'Asia/Baghdad', label: 'Baghdad, Iraq', city: 'Baghdad', region: 'AST' },
  { value: 'Asia/Jerusalem', label: 'Jerusalem, Israel', city: 'Jerusalem', region: 'IST' },
  { value: 'Asia/Beirut', label: 'Beirut, Lebanon', city: 'Beirut', region: 'EET' },
  { value: 'Asia/Damascus', label: 'Damascus, Syria', city: 'Damascus', region: 'EET' },
  { value: 'Asia/Amman', label: 'Amman, Jordan', city: 'Amman', region: 'EET' },
  { value: 'Asia/Yerevan', label: 'Yerevan, Armenia', city: 'Yerevan', region: 'AMT' },
  { value: 'Asia/Baku', label: 'Baku, Azerbaijan', city: 'Baku', region: 'AZT' },
  
  // Central Asia
  { value: 'Asia/Karachi', label: 'Karachi, Pakistan', city: 'Karachi', region: 'PKT' },
  { value: 'Asia/Islamabad', label: 'Islamabad, Pakistan', city: 'Islamabad', region: 'PKT' },
  { value: 'Asia/Kabul', label: 'Kabul, Afghanistan', city: 'Kabul', region: 'AFT' },
  { value: 'Asia/Tashkent', label: 'Tashkent, Uzbekistan', city: 'Tashkent', region: 'UZT' },
  { value: 'Asia/Dushanbe', label: 'Dushanbe, Tajikistan', city: 'Dushanbe', region: 'TJT' },
  { value: 'Asia/Ashgabat', label: 'Ashgabat, Turkmenistan', city: 'Ashgabat', region: 'TMT' },
  { value: 'Asia/Bishkek', label: 'Bishkek, Kyrgyzstan', city: 'Bishkek', region: 'KGT' },
  { value: 'Asia/Almaty', label: 'Almaty, Kazakhstan', city: 'Almaty', region: 'ALMT' },
  
  // South Asia
  { value: 'Asia/Kolkata', label: 'Mumbai, India', city: 'Mumbai', region: 'IST' },
  { value: 'Asia/Delhi', label: 'New Delhi, India', city: 'New Delhi', region: 'IST' },
  { value: 'Asia/Bangalore', label: 'Bangalore, India', city: 'Bangalore', region: 'IST' },
  { value: 'Asia/Chennai', label: 'Chennai, India', city: 'Chennai', region: 'IST' },
  { value: 'Asia/Kolkata', label: 'Kolkata, India', city: 'Kolkata', region: 'IST' },
  { value: 'Asia/Hyderabad', label: 'Hyderabad, India', city: 'Hyderabad', region: 'IST' },
  { value: 'Asia/Colombo', label: 'Colombo, Sri Lanka', city: 'Colombo', region: 'IST' },
  { value: 'Asia/Dhaka', label: 'Dhaka, Bangladesh', city: 'Dhaka', region: 'BST' },
  { value: 'Asia/Kathmandu', label: 'Kathmandu, Nepal', city: 'Kathmandu', region: 'NPT' },
  { value: 'Asia/Thimphu', label: 'Thimphu, Bhutan', city: 'Thimphu', region: 'BTT' },
  
  // Southeast Asia
  { value: 'Asia/Bangkok', label: 'Bangkok, Thailand', city: 'Bangkok', region: 'ICT' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Ho Chi Minh City, Vietnam', city: 'Ho Chi Minh City', region: 'ICT' },
  { value: 'Asia/Hanoi', label: 'Hanoi, Vietnam', city: 'Hanoi', region: 'ICT' },
  { value: 'Asia/Phnom_Penh', label: 'Phnom Penh, Cambodia', city: 'Phnom Penh', region: 'ICT' },
  { value: 'Asia/Vientiane', label: 'Vientiane, Laos', city: 'Vientiane', region: 'ICT' },
  { value: 'Asia/Yangon', label: 'Yangon, Myanmar', city: 'Yangon', region: 'MMT' },
  { value: 'Asia/Singapore', label: 'Singapore', city: 'Singapore', region: 'SGT' },
  { value: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur, Malaysia', city: 'Kuala Lumpur', region: 'MYT' },
  { value: 'Asia/Jakarta', label: 'Jakarta, Indonesia', city: 'Jakarta', region: 'WIB' },
  { value: 'Asia/Bandung', label: 'Bandung, Indonesia', city: 'Bandung', region: 'WIB' },
  { value: 'Asia/Surabaya', label: 'Surabaya, Indonesia', city: 'Surabaya', region: 'WIB' },
  { value: 'Asia/Makassar', label: 'Makassar, Indonesia', city: 'Makassar', region: 'WITA' },
  { value: 'Asia/Jayapura', label: 'Jayapura, Indonesia', city: 'Jayapura', region: 'WIT' },
  { value: 'Asia/Manila', label: 'Manila, Philippines', city: 'Manila', region: 'PHT' },
  { value: 'Asia/Brunei', label: 'Bandar Seri Begawan, Brunei', city: 'Bandar Seri Begawan', region: 'BNT' },
  
  // East Asia
  { value: 'Asia/Shanghai', label: 'Shanghai, China', city: 'Shanghai', region: 'CST' },
  { value: 'Asia/Beijing', label: 'Beijing, China', city: 'Beijing', region: 'CST' },
  { value: 'Asia/Guangzhou', label: 'Guangzhou, China', city: 'Guangzhou', region: 'CST' },
  { value: 'Asia/Shenzhen', label: 'Shenzhen, China', city: 'Shenzhen', region: 'CST' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong', city: 'Hong Kong', region: 'HKT' },
  { value: 'Asia/Macau', label: 'Macau', city: 'Macau', region: 'CST' },
  { value: 'Asia/Taipei', label: 'Taipei, Taiwan', city: 'Taipei', region: 'CST' },
  { value: 'Asia/Tokyo', label: 'Tokyo, Japan', city: 'Tokyo', region: 'JST' },
  { value: 'Asia/Seoul', label: 'Seoul, South Korea', city: 'Seoul', region: 'KST' },
  { value: 'Asia/Pyongyang', label: 'Pyongyang, North Korea', city: 'Pyongyang', region: 'KST' },
  { value: 'Asia/Ulaanbaatar', label: 'Ulaanbaatar, Mongolia', city: 'Ulaanbaatar', region: 'ULAT' },
  
  // Australia & Pacific
  { value: 'Australia/Sydney', label: 'Sydney, Australia', city: 'Sydney', region: 'AEDT/AEST' },
  { value: 'Australia/Melbourne', label: 'Melbourne, Australia', city: 'Melbourne', region: 'AEDT/AEST' },
  { value: 'Australia/Brisbane', label: 'Brisbane, Australia', city: 'Brisbane', region: 'AEST' },
  { value: 'Australia/Perth', label: 'Perth, Australia', city: 'Perth', region: 'AWST' },
  { value: 'Australia/Adelaide', label: 'Adelaide, Australia', city: 'Adelaide', region: 'ACDT/ACST' },
  { value: 'Australia/Darwin', label: 'Darwin, Australia', city: 'Darwin', region: 'ACST' },
  { value: 'Australia/Hobart', label: 'Hobart, Australia', city: 'Hobart', region: 'AEDT/AEST' },
  { value: 'Pacific/Auckland', label: 'Auckland, New Zealand', city: 'Auckland', region: 'NZDT/NZST' },
  { value: 'Pacific/Wellington', label: 'Wellington, New Zealand', city: 'Wellington', region: 'NZDT/NZST' },
  { value: 'Pacific/Christchurch', label: 'Christchurch, New Zealand', city: 'Christchurch', region: 'NZDT/NZST' },
  { value: 'Pacific/Fiji', label: 'Suva, Fiji', city: 'Suva', region: 'FJT' },
  { value: 'Pacific/Guam', label: 'Hagåtña, Guam', city: 'Hagåtña', region: 'ChST' },
  { value: 'Pacific/Port_Moresby', label: 'Port Moresby, Papua New Guinea', city: 'Port Moresby', region: 'PGT' },
  { value: 'Pacific/Noumea', label: 'Nouméa, New Caledonia', city: 'Nouméa', region: 'NCT' },
  { value: 'Pacific/Tahiti', label: 'Papeete, French Polynesia', city: 'Papeete', region: 'TAHT' },
  { value: 'Pacific/Apia', label: 'Apia, Samoa', city: 'Apia', region: 'WST' },
  { value: 'Pacific/Tongatapu', label: "Nuku'alofa, Tonga", city: "Nuku'alofa", region: 'TOT' },
  
  // Africa
  { value: 'Africa/Cairo', label: 'Cairo, Egypt', city: 'Cairo', region: 'EET' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg, South Africa', city: 'Johannesburg', region: 'SAST' },
  { value: 'Africa/Cape_Town', label: 'Cape Town, South Africa', city: 'Cape Town', region: 'SAST' },
  { value: 'Africa/Lagos', label: 'Lagos, Nigeria', city: 'Lagos', region: 'WAT' },
  { value: 'Africa/Nairobi', label: 'Nairobi, Kenya', city: 'Nairobi', region: 'EAT' },
  { value: 'Africa/Casablanca', label: 'Casablanca, Morocco', city: 'Casablanca', region: 'WET' },
  { value: 'Africa/Tunis', label: 'Tunis, Tunisia', city: 'Tunis', region: 'CET' },
  { value: 'Africa/Algiers', label: 'Algiers, Algeria', city: 'Algiers', region: 'CET' },
  { value: 'Africa/Accra', label: 'Accra, Ghana', city: 'Accra', region: 'GMT' },
  { value: 'Africa/Addis_Ababa', label: 'Addis Ababa, Ethiopia', city: 'Addis Ababa', region: 'EAT' },
  { value: 'Africa/Dar_es_Salaam', label: 'Dar es Salaam, Tanzania', city: 'Dar es Salaam', region: 'EAT' },
  { value: 'Africa/Kampala', label: 'Kampala, Uganda', city: 'Kampala', region: 'EAT' },
  { value: 'Africa/Khartoum', label: 'Khartoum, Sudan', city: 'Khartoum', region: 'CAT' },
  { value: 'Africa/Dakar', label: 'Dakar, Senegal', city: 'Dakar', region: 'GMT' },
  { value: 'Africa/Abidjan', label: 'Abidjan, Ivory Coast', city: 'Abidjan', region: 'GMT' },
  { value: 'Africa/Luanda', label: 'Luanda, Angola', city: 'Luanda', region: 'WAT' },
  { value: 'Africa/Douala', label: 'Douala, Cameroon', city: 'Douala', region: 'WAT' },
  { value: 'Africa/Kinshasa', label: 'Kinshasa, DRC', city: 'Kinshasa', region: 'WAT' },
  { value: 'Africa/Lubumbashi', label: 'Lubumbashi, DRC', city: 'Lubumbashi', region: 'CAT' },
  { value: 'Africa/Maputo', label: 'Maputo, Mozambique', city: 'Maputo', region: 'CAT' },
  { value: 'Africa/Harare', label: 'Harare, Zimbabwe', city: 'Harare', region: 'CAT' },
  { value: 'Africa/Gaborone', label: 'Gaborone, Botswana', city: 'Gaborone', region: 'CAT' },
  { value: 'Africa/Windhoek', label: 'Windhoek, Namibia', city: 'Windhoek', region: 'CAT' },
  
  // Atlantic
  { value: 'Atlantic/Reykjavik', label: 'Reykjavik, Iceland', city: 'Reykjavik', region: 'GMT' },
  { value: 'Atlantic/Azores', label: 'Ponta Delgada, Azores', city: 'Ponta Delgada', region: 'AZOT' },
  { value: 'Atlantic/Canary', label: 'Las Palmas, Canary Islands', city: 'Las Palmas', region: 'WET' },
  { value: 'Atlantic/Cape_Verde', label: 'Praia, Cape Verde', city: 'Praia', region: 'CVT' },
  { value: 'Atlantic/Bermuda', label: 'Hamilton, Bermuda', city: 'Hamilton', region: 'AST' },
  
  // Indian Ocean
  { value: 'Indian/Mauritius', label: 'Port Louis, Mauritius', city: 'Port Louis', region: 'MUT' },
  { value: 'Indian/Reunion', label: 'Saint-Denis, Réunion', city: 'Saint-Denis', region: 'RET' },
  { value: 'Indian/Maldives', label: 'Malé, Maldives', city: 'Malé', region: 'MVT' },
  { value: 'Indian/Seychelles', label: 'Victoria, Seychelles', city: 'Victoria', region: 'SCT' },
];

// Helper function to get coordinates for a timezone (simplified mapping)
// In production, you'd want to use a geocoding service or more comprehensive mapping
export function getTimezoneCoordinates(timezone: string): { lat: number; lon: number } | null {
  const coordMap: Record<string, { lat: number; lon: number }> = {
    'UTC': { lat: 51.4779, lon: 0.0 },
    'America/New_York': { lat: 40.7128, lon: -74.0060 },
    'America/Chicago': { lat: 41.8781, lon: -87.6298 },
    'America/Denver': { lat: 39.7392, lon: -104.9903 },
    'America/Los_Angeles': { lat: 34.0522, lon: -118.2437 },
    'America/Toronto': { lat: 43.6532, lon: -79.3832 },
    'America/Vancouver': { lat: 49.2827, lon: -123.1207 },
    'America/Mexico_City': { lat: 19.4326, lon: -99.1332 },
    'America/Sao_Paulo': { lat: -23.5505, lon: -46.6333 },
    'America/Buenos_Aires': { lat: -34.6037, lon: -58.3816 },
    'America/Lima': { lat: -12.0464, lon: -77.0428 },
    'America/Bogota': { lat: 4.7110, lon: -74.0721 },
    'America/Santiago': { lat: -33.4489, lon: -70.6693 },
    'Europe/London': { lat: 51.5074, lon: -0.1278 },
    'Europe/Paris': { lat: 48.8566, lon: 2.3522 },
    'Europe/Berlin': { lat: 52.5200, lon: 13.4050 },
    'Europe/Rome': { lat: 41.9028, lon: 12.4964 },
    'Europe/Madrid': { lat: 40.4168, lon: -3.7038 },
    'Europe/Moscow': { lat: 55.7558, lon: 37.6173 },
    'Asia/Dubai': { lat: 25.2048, lon: 55.2708 },
    'Asia/Riyadh': { lat: 24.7136, lon: 46.6753 },
    'Asia/Karachi': { lat: 24.8607, lon: 67.0011 },
    'Asia/Kolkata': { lat: 19.0760, lon: 72.8777 },
    'Asia/Delhi': { lat: 28.6139, lon: 77.2090 },
    'Asia/Dhaka': { lat: 23.8103, lon: 90.4125 },
    'Asia/Bangkok': { lat: 13.7563, lon: 100.5018 },
    'Asia/Singapore': { lat: 1.3521, lon: 103.8198 },
    'Asia/Jakarta': { lat: -6.2088, lon: 106.8456 },
    'Asia/Manila': { lat: 14.5995, lon: 120.9842 },
    'Asia/Shanghai': { lat: 31.2304, lon: 121.4737 },
    'Asia/Beijing': { lat: 39.9042, lon: 116.4074 },
    'Asia/Hong_Kong': { lat: 22.3193, lon: 114.1694 },
    'Asia/Tokyo': { lat: 35.6762, lon: 139.6503 },
    'Asia/Seoul': { lat: 37.5665, lon: 126.9780 },
    'Australia/Sydney': { lat: -33.8688, lon: 151.2093 },
    'Australia/Melbourne': { lat: -37.8136, lon: 144.9631 },
    'Australia/Brisbane': { lat: -27.4698, lon: 153.0251 },
    'Australia/Perth': { lat: -31.9505, lon: 115.8605 },
    'Pacific/Auckland': { lat: -36.8485, lon: 174.7633 },
    'Pacific/Honolulu': { lat: 21.3099, lon: -157.8581 },
    'Africa/Cairo': { lat: 30.0444, lon: 31.2357 },
    'Africa/Johannesburg': { lat: -26.2041, lon: 28.0473 },
    'Africa/Lagos': { lat: 6.5244, lon: 3.3792 },
    'Africa/Nairobi': { lat: -1.2921, lon: 36.8219 },
    'Africa/Casablanca': { lat: 33.5731, lon: -7.5898 },
  };
  
  return coordMap[timezone] || null;
}

